-- GOTCHA game schema
-- Run this once in the Supabase SQL Editor (Project: nmmshjdknmuzpgpquwec)
-- before using the app. It creates the tables the app reads/writes and
-- enables Realtime so every player's device stays in sync.
--
-- This script is safe to re-run on an existing database: table/column
-- creation uses IF NOT EXISTS so it will pick up new columns (like
-- student_id / photo_url) without touching existing data.

create table if not exists public.houses (
  id bigint generated by default as identity primary key,
  name text not null unique,
  points integer not null default 0
);

create table if not exists public.players (
  id bigint generated by default as identity primary key,
  name text not null,
  house text not null,
  status text not null default 'alive',
  target_id bigint references public.players(id) on delete set null,
  eliminations integer not null default 0,
  has_golden_dart boolean not null default false
);

-- Student ID players use to log themselves in and see their target, and a
-- public URL for their uploaded photo (see the storage bucket below).
alter table public.players add column if not exists student_id text;
alter table public.players add column if not exists photo_url text;

-- Timestamp of when a player's current target was assigned by the system
-- (Start Game / elimination / revive / reassignment). Kept for reference,
-- but the 24-hour expiration sweep no longer reads this directly.
alter table public.players add column if not exists target_assigned_at timestamptz;

-- Timestamp of when the PLAYER actually tapped "Acquire Target" for their
-- current target. Null until they do, which is what gates the reveal
-- behind the Acquire Target button. This - not target_assigned_at - is
-- what the 24-hour expiration sweep reads, so every player's window
-- starts from when they personally engaged, not a shared assignment time.
-- Reset to null any time a player's target_id changes, so they have to
-- acquire it again.
alter table public.players add column if not exists target_acquired_at timestamptz;

create unique index if not exists players_student_id_key
  on public.players (student_id)
  where student_id is not null;

create table if not exists public.game_state (
  id integer primary key default 1,
  active boolean not null default false,
  constraint game_state_single_row check (id = 1)
);

insert into public.game_state (id, active)
values (1, false)
on conflict (id) do nothing;

-- Shared roster/settings tables. These are the SAME tables the Timesheet
-- app (cabgcu/timesheet, migration.sql) reads and writes in this project —
-- that's how "Sync Roster" connects the two apps: this app never keeps its
-- own copy of the roster, it just reads whichever academic year Timesheet
-- has marked active. Declared here too (IF NOT EXISTS, no drops) so this
-- script is safe to run standalone even if Timesheet's migration hasn't
-- been run yet in this project; columns mirror Timesheet's schema exactly
-- so either script can run first without breaking the other's writes.
create table if not exists public.roster (
  id bigint generated by default as identity primary key,
  academic_year text not null,
  student_id text not null,
  name text not null,
  team text not null,
  email text,
  position text,
  unique (academic_year, student_id)
);

create table if not exists public.settings (
  key text primary key,
  value text
);

insert into public.settings (key, value)
values ('ActiveYear', '2025-2026')
on conflict (key) do nothing;

-- Row Level Security. This app has no real user auth (the "Admin" screen
-- is just a client-side password prompt), so writes are left open to the
-- anon/publishable key to match that trust model. Tighten this later with
-- Supabase Auth if you want real admin-only writes.
alter table public.houses enable row level security;
alter table public.players enable row level security;
alter table public.game_state enable row level security;

-- roster/settings are owned by the Timesheet app's trust model (anon key,
-- no RLS) — matched here so this app's anon key can read them too.
alter table public.roster disable row level security;
alter table public.settings disable row level security;

drop policy if exists "Public read houses" on public.houses;
drop policy if exists "Public write houses" on public.houses;
create policy "Public read houses" on public.houses for select using (true);
create policy "Public write houses" on public.houses for all using (true) with check (true);

drop policy if exists "Public read players" on public.players;
drop policy if exists "Public write players" on public.players;
create policy "Public read players" on public.players for select using (true);
create policy "Public write players" on public.players for all using (true) with check (true);

drop policy if exists "Public read game_state" on public.game_state;
drop policy if exists "Public write game_state" on public.game_state;
create policy "Public read game_state" on public.game_state for select using (true);
create policy "Public write game_state" on public.game_state for all using (true) with check (true);

-- Enable Realtime so the leaderboard/dashboard update live on every device.
-- SET (not ADD) declares the full table list outright instead of erroring
-- when a table is already published, so this single statement is safe to
-- re-run. It assumes these three tables are the only ones this project's
-- supabase_realtime publication should carry — add to the list here if a
-- future table needs realtime too.
alter publication supabase_realtime set table public.houses, public.players, public.game_state;

-- Storage bucket for player photos uploaded from the Admin roster screen.
-- Public + open writes to match the same no-auth trust model as the
-- tables above (anyone with the anon key can read/write). The app names
-- objects "<player-id>-<timestamp>.<ext>", so there's no collision risk
-- even with open write access.
insert into storage.buckets (id, name, public)
values ('player-photos', 'player-photos', true)
on conflict (id) do nothing;

drop policy if exists "Public read player photos" on storage.objects;
drop policy if exists "Public upload player photos" on storage.objects;
drop policy if exists "Public update player photos" on storage.objects;
create policy "Public read player photos" on storage.objects
  for select using (bucket_id = 'player-photos');
create policy "Public upload player photos" on storage.objects
  for insert with check (bucket_id = 'player-photos');
create policy "Public update player photos" on storage.objects
  for update using (bucket_id = 'player-photos') with check (bucket_id = 'player-photos');
