-- GOTCHA game schema
-- Run this once in the Supabase SQL Editor (Project: nmmshjdknmuzpgpquwec)
-- before using the app. It creates the tables the app reads/writes and
-- enables Realtime so every player's device stays in sync.
--
-- This script is safe to re-run on an existing database: table/column
-- creation uses IF NOT EXISTS so it will pick up new columns (like
-- student_id / photo_url) without touching existing data.

create table if not exists public.houses (
  id bigint generated by default as identity primary key,
  name text not null unique,
  points integer not null default 0
);

create table if not exists public.players (
  id bigint generated by default as identity primary key,
  name text not null,
  house text not null,
  status text not null default 'alive',
  target_id bigint references public.players(id) on delete set null,
  eliminations integer not null default 0,
  has_golden_dart boolean not null default false
);

-- Student ID players use to log themselves in and see their target, and a
-- public URL for their uploaded photo (see the storage bucket below).
alter table public.players add column if not exists student_id text;
alter table public.players add column if not exists photo_url text;

create unique index if not exists players_student_id_key
  on public.players (student_id)
  where student_id is not null;

create table if not exists public.game_state (
  id integer primary key default 1,
  active boolean not null default false,
  constraint game_state_single_row check (id = 1)
);

insert into public.game_state (id, active)
values (1, false)
on conflict (id) do nothing;

-- Row Level Security. This app has no real user auth (the "Admin" screen
-- is just a client-side password prompt), so writes are left open to the
-- anon/publishable key to match that trust model. Tighten this later with
-- Supabase Auth if you want real admin-only writes.
alter table public.houses enable row level security;
alter table public.players enable row level security;
alter table public.game_state enable row level security;

drop policy if exists "Public read houses" on public.houses;
drop policy if exists "Public write houses" on public.houses;
create policy "Public read houses" on public.houses for select using (true);
create policy "Public write houses" on public.houses for all using (true) with check (true);

drop policy if exists "Public read players" on public.players;
drop policy if exists "Public write players" on public.players;
create policy "Public read players" on public.players for select using (true);
create policy "Public write players" on public.players for all using (true) with check (true);

drop policy if exists "Public read game_state" on public.game_state;
drop policy if exists "Public write game_state" on public.game_state;
create policy "Public read game_state" on public.game_state for select using (true);
create policy "Public write game_state" on public.game_state for all using (true) with check (true);

-- Enable Realtime so the leaderboard/dashboard update live on every device.
-- ALTER PUBLICATION ... ADD TABLE has no IF NOT EXISTS, so guard each one
-- against pg_publication_tables to keep this script re-runnable.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'houses'
  ) then
    alter publication supabase_realtime add table public.houses;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'players'
  ) then
    alter publication supabase_realtime add table public.players;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'game_state'
  ) then
    alter publication supabase_realtime add table public.game_state;
  end if;
end $$;

-- Storage bucket for player photos uploaded from the Admin roster screen.
-- Public + open writes to match the same no-auth trust model as the
-- tables above (anyone with the anon key can read/write). The app names
-- objects "<player-id>-<timestamp>.<ext>", so there's no collision risk
-- even with open write access.
insert into storage.buckets (id, name, public)
values ('player-photos', 'player-photos', true)
on conflict (id) do nothing;

drop policy if exists "Public read player photos" on storage.objects;
drop policy if exists "Public upload player photos" on storage.objects;
drop policy if exists "Public update player photos" on storage.objects;
create policy "Public read player photos" on storage.objects
  for select using (bucket_id = 'player-photos');
create policy "Public upload player photos" on storage.objects
  for insert with check (bucket_id = 'player-photos');
create policy "Public update player photos" on storage.objects
  for update using (bucket_id = 'player-photos') with check (bucket_id = 'player-photos');
