-- GOTCHA game schema
-- Run this once in the Supabase SQL Editor (Project: nmmshjdknmuzpgpquwec)
-- before using the app. It creates the tables the app reads/writes and
-- enables Realtime so every player's device stays in sync.

create table if not exists public.houses (
  id bigint generated by default as identity primary key,
  name text not null unique,
  points integer not null default 0
);

create table if not exists public.players (
  id bigint generated by default as identity primary key,
  name text not null,
  house text not null,
  status text not null default 'alive',
  target_id bigint references public.players(id) on delete set null,
  eliminations integer not null default 0,
  has_golden_dart boolean not null default false
);

create table if not exists public.game_state (
  id integer primary key default 1,
  active boolean not null default false,
  constraint game_state_single_row check (id = 1)
);

insert into public.game_state (id, active)
values (1, false)
on conflict (id) do nothing;

-- Row Level Security. This app has no real user auth (the "Admin" screen
-- is just a client-side password prompt), so writes are left open to the
-- anon/publishable key to match that trust model. Tighten this later with
-- Supabase Auth if you want real admin-only writes.
alter table public.houses enable row level security;
alter table public.players enable row level security;
alter table public.game_state enable row level security;

drop policy if exists "Public read houses" on public.houses;
drop policy if exists "Public write houses" on public.houses;
create policy "Public read houses" on public.houses for select using (true);
create policy "Public write houses" on public.houses for all using (true) with check (true);

drop policy if exists "Public read players" on public.players;
drop policy if exists "Public write players" on public.players;
create policy "Public read players" on public.players for select using (true);
create policy "Public write players" on public.players for all using (true) with check (true);

drop policy if exists "Public read game_state" on public.game_state;
drop policy if exists "Public write game_state" on public.game_state;
create policy "Public read game_state" on public.game_state for select using (true);
create policy "Public write game_state" on public.game_state for all using (true) with check (true);

-- Enable Realtime so the leaderboard/dashboard update live on every device.
alter publication supabase_realtime add table public.houses;
alter publication supabase_realtime add table public.players;
alter publication supabase_realtime add table public.game_state;
